"""Add video progress fields

Revision ID: de1446e45db4
Revises: 
Create Date: 2025-08-28 09:23:59.672571

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de1446e45db4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 只添加播放进度相关字段，不修改其他表结构
    op.add_column('videos', sa.Column('last_position', sa.Float(), nullable=True, default=0.0))
    op.add_column('videos', sa.Column('watch_progress', sa.Float(), nullable=True, default=0.0))
    op.add_column('videos', sa.Column('last_watched_at', sa.DateTime(), nullable=True))
    op.add_column('videos', sa.Column('is_completed', sa.Boolean(), nullable=True, default=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 只删除播放进度相关字段
    op.drop_column('videos', 'is_completed')
    op.drop_column('videos', 'last_watched_at')
    op.drop_column('videos', 'watch_progress')
    op.drop_column('videos', 'last_position')
    # ### end Alembic commands ###
